### ISSUE TITLE
Image Show 1.49.2 - Ftal Error

### ISSUE THREAD

**Issue by tony2015** [GavickPro/Image-Show#72]
Just installed and when i run this in Module Manager (Joomla) 3.3.6 i receive the following error message;

Fatal error: Call to undefined method JFactory::getXMLParser() in /XXXX/XXXX/modules/mod_image_show_gk4/admin/elements/config.php on line 28

The XXXX i have placed though is the directory file.

The screen actually does not look like a normal module screen.

Tony

**Comment by tony2015** [comment]
Hello Tomasz.

Thank-you for your timely response.

I installed 3x yet there are still issues. Image Show GK4 installs however
cannot be seen in my module manager? Even when i do a search, both line by
line and via the search function in Joomla module manager, it does not
appear despite being declared successfully installed. However when i go to
extension manager and search for it through 'manage' it is there!

I wanted to see if this was a typical problem thus installed your Grid GK5
module, and it works fine.

Unsure of the issue. Please kindly advise.


Tony

**Comment by dziudek** [comment]
Did you tried to create a new instance of the module?

**Comment by tony2015** [comment]
Hello.

Yes I downloaded version 3x as advised and installed through manager.

Should I perhaps clear the cache?


Tony

On Monday, January 5, 2015, Tomasz Dziuda <notifications@github.com> wrote:

> Did you tried to create a new instance of the module?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GavickPro/Image-Show/issues/72#issuecomment-68682978>.
>


-- 
Thank-you.

Tony


Sent from Gmail Mobile

**Comment by dziudek** [comment]
No, I mean that in the module manager you can create w new module by clicking the "New" button - the you should see Image Show GK4 on the list.

**Comment by tony2015** [comment]
Ok will check and revert. Won't be for a few days as I am currently away in
leave.

Even so, should it no still be viewable in module manager as per any
installed module? Why is this different?

Thank you again.

Tony

On Tuesday, January 6, 2015, Tomasz Dziuda <notifications@github.com> wrote:

> No, I mean that in the module manager you can create w new module by
> clicking the "New" button - the you should see Image Show GK4 on the list.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GavickPro/Image-Show/issues/72#issuecomment-68706057>.
>


-- 
Thank-you.

Tony


Sent from Gmail Mobile

**Comment by dziudek** [comment]
I don't know why - I have the same issue with other installed modules sometimes.

**Comment by tony2015** [comment]
Hello Tomasz.

Using 'New' still did not work.

However, i uninstalled it. Cleared and purged cache, then reinstalled and
it now appears.

FYI in case others have same problems.

Thank-you.


T
