### ISSUE TITLE
Missing translation key.

### ISSUE THREAD

**Issue by Cyberek** [GavickPro/Image-Show#74]
I bet I have already submitted this issue ;)
In language file:
MOD_IMAGE_SHOW_PHOTO_READMORE
key is missing - it is used as default when "Url" field of a slide doesn't have text, only link.

**Comment by dziudek** [comment]
Added: https://github.com/GavickPro/Image-Show/commit/783cd39ab2ae79a37dede7144a2f4601ff914ef0

I was sure that this issue was fixed long time ago :)

It will be released with v.1.53
