### ISSUE TITLE
Change Module Style issue

### ISSUE THREAD

**Issue by DiamChris** [GavickPro/Image-Show#76]
Hello, 
I had purchase Joomla Template Startup about two years ago and I was very satisfied with your template.
The last days I tried to redesign my main web site (www.artifico.gr) I update Image Show GK4 and every time I tried to change Image Show GK4 style, the appearence messed up. It works only for gk_startup.
The problem existes because I have purchase only Stratup template or there is a problem with my configuration ?

If you want to test my configuration I have made a test environment in test.artifico.gr

Best regards
Diamantis Christou

**Comment by dziudek** [comment]
Hello,

The Startup template has a specific structure and only the gk_startup style will work without any changes. Other styles will require custom works which are beyond of our standard technical support.

**Comment by DiamChris** [comment]
Ok, that isn't a big issue. Style gk_startup is acceptable for my update. 
But I have one more question. 
I am interesting about to purchase "All Themes -Paid only once" but I want to clarify the usage of Image Show GK4. Other templates have the same restrictions with Startup Template? or I can choose freely different styles?

**Comment by dziudek** [comment]
Every template is designed to use a specific style, but if you enable the use of default CSS in Image Show then other styles should also work, but probably will need some CSS adjustments to the specific template style.

**Comment by dziudek** [comment]
Some exception are templates like Game, University, Photo - where Image Show GK4 is an important part of the template.

**Comment by DiamChris** [comment]
Ok, that is clear enough.
Thank you for your quick response.
